## CLEAN DATAS FOR MOVIE RECOMMENDATION ASSISTANT

In [294]:
#pip install -r ./requirements.txt

In [295]:
import numpy as np
import pandas as pd

DATA CLEANING and INFORMATION:
- Load data ✅
- Find Missing datas ✅
- Find duplicated datas ✅
- Find Structural errors ✅
- See whether datas are formatted according to standards ✅
- Impossible values / Outliers ✅

In [296]:
data = pd.read_csv('imdb_top_1000.csv')
df = pd.DataFrame(data)

In [297]:
df.info()
#certificate, meta_score, gross ada yg null, types ada yg aneh (release year, runtime, gross)
#semua column tulisannya sama: capitalize and use _ --> ubah semua capitalize jadi lowercase

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 520.0 KB

In [298]:
print(df[df.duplicated()])
# ga ada duplicated secara umum = Empty dataframe

Empty DataFrame
Columns: [Poster_Link, Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Overview, Meta_score, Director, Star1, Star2, Star3, Star4, No_of_Votes, Gross]
Index: []

In [299]:
#Posterlink will not be dropped for multimodal system (image similarity)
#Drop metascore and gross because I want to make the chatbot just about film and find a good film
df = df.drop(['Meta_score', 'Gross'],axis=1)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Director       1000 non-null   str
 9   Star1          1000 non-null   str
 10  Star2          1000 non-null   str
 11  Star3          1000 non-null   str
 12  Star4          1000 non-null   str
 13  No_of_Votes    1000 non-null   int64
dtypes: float64(1), int64(1), str(12)
memory usage: 496.6 KB

In [300]:
df['Certificate']

0           A
1           A
2          UA
3           A
4           U
        ...
995         A
996         G
997    Passed
998       NaN
999       NaN
Name: Certificate, Length: 1000, dtype: str

In [301]:
#Sisa missing itu Certificate aja
#Fill missing datas with (certificate = unknown) krn type:str
df = df.fillna('unknown')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    1000 non-null   str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Director       1000 non-null   str
 9   Star1          1000 non-null   str
 10  Star2          1000 non-null   str
 11  Star3          1000 non-null   str
 12  Star4          1000 non-null   str
 13  No_of_Votes    1000 non-null   int64
dtypes: float64(1), int64(1), str(12)
memory usage: 497.1 KB

In [302]:
#CHECK!
df['Certificate']

0            A
1            A
2           UA
3            A
4            U
        ...
995          A
996          G
997     Passed
998    unknown
999    unknown
Name: Certificate, Length: 1000, dtype: str

In [303]:
df['Runtime'].value_counts()

Runtime
130 min    23
100 min    23
101 min    22
113 min    22
129 min    22
           ..
69 min      1
70 min      1
242 min     1
79 min      1
78 min      1
Name: count, Length: 140, dtype: int64

In [304]:
#Change Runtime to Runtime (Min) so delete all the min in values
df['Runtime_min'] = df['Runtime'].str.replace(' min', '', regex=True)
df['Runtime_min'] = df['Runtime_min'].str.strip() #whitespace deletion
df['Runtime_min'].value_counts

<bound method IndexOpsMixin.value_counts of 0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime_min, Length: 1000, dtype: str>

In [305]:
#Change Runtime_min to INT and drop Runtime
df['Runtime_min'] = df['Runtime_min'].astype(int)
df = df.drop('Runtime', axis=1)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   str
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   Star2          1000 non-null   str
 10  Star3          1000 non-null   str
 11  Star4          1000 non-null   str
 12  No_of_Votes    1000 non-null   int64
 13  Runtime_min    1000 non-null   int64
dtypes: float64(1), int64(2), str(11)
memory usage: 490.5 KB

In [306]:
# cek semua unique: poster link sama series title ga ada
df['Released_Year'].unique()
# ada PG sendiri dan typenya str

<ArrowStringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943',
   'PG']
Length: 100, dtype: str

In [307]:
#Cari PG dan ganti PG sesuai filmnya
df[df['Released_Year'] == 'PG']

,Poster_Link,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Runtime_min
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,140

In [308]:
df.loc[966, 'Released_Year'] = '1970'

In [309]:
#CHECK!
df[df['Released_Year'] == '1970']

,Poster_Link,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Runtime_min
423,https://m.media-amazon.com/images/M/MV5BODFlYz...,Il conformista,1970,UA,Drama,8.0,A weak-willed Italian man becomes a fascist fl...,Bernardo Bertolucci,Jean-Louis Trintignant,Stefania Sandrelli,Gastone Moschin,Enzo Tarascio,27067,113
542,https://m.media-amazon.com/images/M/MV5BMmNhZm...,Patton,1970,U,"Biography, Drama, War",7.9,The World War II phase of the career of contro...,Franklin J. Schaffner,George C. Scott,Karl Malden,Stephen Young,Michael Strong,93741,172
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,1970,U,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,140
991,https://m.media-amazon.com/images/M/MV5BMzAyND...,Kelly's Heroes,1970,GP,"Adventure, Comedy, War",7.6,A group of U.S. soldiers sneaks across enemy l...,Brian G. Hutton,Clint Eastwood,Telly Savalas,Don Rickles,Carroll O'Connor,45338,144

In [310]:
#ubah type jadi int
df['Released_Year'] = df['Released_Year'].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   int64
 3   Certificate    1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   str
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   Star2          1000 non-null   str
 10  Star3          1000 non-null   str
 11  Star4          1000 non-null   str
 12  No_of_Votes    1000 non-null   int64
 13  Runtime_min    1000 non-null   int64
dtypes: float64(1), int64(3), str(10)
memory usage: 486.6 KB

In [311]:
#CHECK whether the years are >2026
year_check = (df['Released_Year'] > 2026)
year_check.unique()

array([False])

In [312]:
df['Certificate'].unique()
#hybrid collection of ratings in India, America and Content Restricted (Unrated, Passed, Approved)
#Must add Content Restriction in agent (add new column for age categories)

<ArrowStringArray>
[       'A',       'UA',        'U',    'PG-13',        'R',  'unknown',
       'PG',        'G',   'Passed',    'TV-14',       '16',    'TV-MA',
  'Unrated',       'GP', 'Approved',    'TV-PG',      'U/A']
Length: 17, dtype: str

In [313]:
def mapping_certificate(cert):
    cert = str(cert).strip().upper()
    mapping = {'U': 'all ages',
               'G': 'all ages',
               'APPROVED': 'all ages',
               'PASSED': 'all ages',
               
               'UA': 'parental guidance',
               'U/A': 'parental guidance',
               'PG': 'parental guidance',
               'TV-PG': 'parental guidance',
               'GP': 'parental guidance',

               'PG-13': '13 years old and above',
               'TV-14': '14 years old and above',
               '16': '16 years old and above',
               
               'R': 'adults only',
               'A': 'adults only',
               'TV-MA': 'adults only',

               'UNRATED': 'not rated',
               'UNKNOWN': 'not rated'}
    
    return mapping.get(cert, 'Not rated')

df['age_group'] = df['Certificate'].apply(mapping_certificate)
df['age_group'].unique()

<ArrowStringArray>
[           'adults only',      'parental guidance',               'all ages',
 '13 years old and above',              'not rated', '14 years old and above',
 '16 years old and above']
Length: 7, dtype: str

In [314]:
#Check!
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   int64
 3   Certificate    1000 non-null   str
 4   Genre          1000 non-null   str
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   str
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   Star2          1000 non-null   str
 10  Star3          1000 non-null   str
 11  Star4          1000 non-null   str
 12  No_of_Votes    1000 non-null   int64
 13  Runtime_min    1000 non-null   int64
 14  age_group      1000 non-null   str
dtypes: float64(1), int64(3), str(11)
memory usage: 505.9 KB

In [315]:
df['Genre'].unique()

<ArrowStringArray>
[                     'Drama',               'Crime, Drama',
       'Action, Crime, Drama',   'Action, Adventure, Drama',
  'Biography, Drama, History',  'Action, Adventure, Sci-Fi',
             'Drama, Romance',                    'Western',
             'Action, Sci-Fi',    'Biography, Crime, Drama',
 ...
     'Action, Adventure, War',     'Drama, Horror, Mystery',
   'Animation, Comedy, Crime',   'Action, Adventure, Crime',
 'Action, Adventure, Mystery',  'Action, Adventure, Family',
     'Action, Crime, Mystery',  'Animation, Drama, Romance',
        'Drama, War, Western',     'Adventure, Comedy, War']
Length: 202, dtype: str

In [316]:
#bagi genrenya jadi list
df['Genre'] = df['Genre'].apply(lambda x: [genres.strip() for genres in x.split(', ')])
df['Genre']

0                         [Drama]
1                  [Crime, Drama]
2          [Action, Crime, Drama]
3                  [Crime, Drama]
4                  [Crime, Drama]
                  ...
995      [Comedy, Drama, Romance]
996              [Drama, Western]
997         [Drama, Romance, War]
998                  [Drama, War]
999    [Crime, Mystery, Thriller]
Name: Genre, Length: 1000, dtype: object

In [317]:
#CHECK!
type(df['Genre'].iloc[1])

list

In [318]:
#make them lowercase
df['Genre'] = df['Genre'].apply(lambda x: [Gen.lower() for Gen in x])
df['Genre']

0                         [drama]
1                  [crime, drama]
2          [action, crime, drama]
3                  [crime, drama]
4                  [crime, drama]
                  ...
995      [comedy, drama, romance]
996              [drama, western]
997         [drama, romance, war]
998                  [drama, war]
999    [crime, mystery, thriller]
Name: Genre, Length: 1000, dtype: object

In [319]:
#Trailing spaces sisa di Director, Stars, Series_Title
col = ['Director', 'Star1', 'Star2', 'Star3', 'Star4', 'Series_Title']
for columns in col:
    end_spaces = df[columns].str.endswith(' ').sum()
    start_spaces = df[columns].str.startswith(' ').sum()

    print(f'{columns} --> end: {end_spaces} ; start: {start_spaces}')

Director --> end: 0 ; start: 0
Star1 --> end: 0 ; start: 0
Star2 --> end: 0 ; start: 0
Star3 --> end: 0 ; start: 0
Star4 --> end: 0 ; start: 0
Series_Title --> end: 0 ; start: 0

In [320]:
#IMDB Rating ga ada masalah
#Search for truncated sentences, weird encoding, low info text manually
df['Overview'].sample(10)

297    An innocent yet pampered young virgin and her ...
995    A young New York socialite becomes interested ...
147    Based on the true story of Jordan Belfort, fro...
734    Adèle's life is changed when she meets Emma, a...
611    A journalist is aided by a young female hacker...
917    A man with a fateful secret embarks on an extr...
247    The people of a small village in Victorian Ind...
913    A high school teacher's experiment to demonstr...
719    Dr. Frankenstein dares to tamper with life and...
570    A Kashmiri woman agrees to marry a Pakistani a...
Name: Overview, dtype: str

In [321]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Runtime_min,age_group
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,[drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,142,adults only
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,"[crime, drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,175,adults only
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,"[action, crime, drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,152,parental guidance
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,"[crime, drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,202,adults only
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,"[crime, drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,96,all ages

In [322]:
#Outliers (Runtime and Rating)
a = len(df[df['Runtime_min'] < 0])
b = len(df[df['Runtime_min'] > 300])
c = len(df[df['IMDB_Rating'] < 0])
d = len(df[df['IMDB_Rating'] > 10])
print(f'Runtime less than 30 mins: {a}')
print(f'Runtime more than 30 mins: {b}')
print(f'IMDB Rating less than 10: {c}')
print(f'IMDB Rating more than 10: {d}')

Runtime less than 30 mins: 0
Runtime more than 30 mins: 1
IMDB Rating less than 10: 0
IMDB Rating more than 10: 0

In [323]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   int64
 3   Certificate    1000 non-null   str
 4   Genre          1000 non-null   object
 5   IMDB_Rating    1000 non-null   float64
 6   Overview       1000 non-null   str
 7   Director       1000 non-null   str
 8   Star1          1000 non-null   str
 9   Star2          1000 non-null   str
 10  Star3          1000 non-null   str
 11  Star4          1000 non-null   str
 12  No_of_Votes    1000 non-null   int64
 13  Runtime_min    1000 non-null   int64
 14  age_group      1000 non-null   str
dtypes: float64(1), int64(3), object(1), str(10)
memory usage: 487.2+ KB

In [324]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Genre,IMDB_Rating,Overview,Director,Star1,Star2,Star3,Star4,No_of_Votes,Runtime_min,age_group
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,[drama],9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,142,adults only
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,"[crime, drama]",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,175,adults only
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,"[action, crime, drama]",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,152,parental guidance
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,"[crime, drama]",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,202,adults only
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,"[crime, drama]",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,96,all ages

In [ ]:
#save cleaned data
#df.to_csv('cleaned_data.csv', index=False)
#load new cleaned data
df = pd.read_csv('./datas/cleaned_data.csv')